# Generated by Django 4.0.6 on 2022-08-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fooditems',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
